# Generated by Django 4.2.5 on 2023-09-08 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0012_alter_productimage_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=32, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=32, verbose_name="Last name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, null=True, verbose_name="Email address"
                    ),
                ),
                ("phone", models.CharField(max_length=12, verbose_name="Mobile phone")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "New"),
                            ("P", "Processing"),
                            ("D", "Delivery"),
                            ("S", "Success"),
                            ("C", "Cancelled"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Paid")),
                ("address", models.CharField()),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Price"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Item quantity"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order item",
                "verbose_name_plural": "Order items",
                "db_table": "order_items",
            },
        ),
    ]
