# Generated by Django 4.2.5 on 2023-09-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=10, verbose_name="Mobile phone"),
        ),
    ]
