# Generated by Django 4.2.9 on 2024-01-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_email_alter_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    ("0", "New"),
                    ("1", "Processing"),
                    ("2", "Delivery"),
                    ("3", "Success"),
                    ("4", "Cancelled"),
                ],
                default="0",
                max_length=1,
                verbose_name="Status",
            ),
        ),
    ]
