# Generated by Django 4.2.9 on 2024-02-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0021_remove_product_categories_remove_product_created_at_and_more",
        ),
        ("order", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="currency",
            field=models.CharField(
                default="EUR", max_length=3, verbose_name="Currency"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="product.productitem",
            ),
        ),
    ]
