# Generated by Django 4.2.9 on 2024-02-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_orderitem_currency_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="currency",
            field=models.CharField(
                default="UAH", max_length=3, verbose_name="Currency"
            ),
        ),
    ]
