# Generated by Django 4.2.9 on 2024-02-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_cartitem_currency_alter_cartitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="currency",
            field=models.CharField(
                default="UAH", max_length=3, verbose_name="Currency"
            ),
        ),
    ]
