# fly.toml app configuration file generated for beautyshop on 2023-08-03T13:13:16+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beautyshop"
primary_region = "waw"

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


[mounts]
  source="media_data"
  destination="/app/src/media/"
