# Generated by Django 4.2.3 on 2023-07-30 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Rating"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Price"
                    ),
                ),
                ("sku", models.PositiveIntegerField(verbose_name="Stock keeping unit")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("I", "In stock"),
                            ("O", "Out of stock"),
                            ("P", "Expected"),
                        ],
                        default="I",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Product",
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Product category",
                "verbose_name_plural": "Product categories",
                "db_table": "product_categories",
            },
        ),
        migrations.CreateModel(
            name="ProductManufacturer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "db_table": "manufacturers",
            },
        ),
        migrations.CreateModel(
            name="ProductCategoryOption",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="options",
                        to="product.productcategory",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        blank=True,
                        db_table="product_options_m2m",
                        related_name="product_options",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product category",
                "verbose_name_plural": "Product categories",
                "db_table": "product_category_options",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                db_table="product_category_m2m",
                related_name="product_categories",
                to="product.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="product.productmanufacturer",
                verbose_name="Manufacturer",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "img_path",
                    models.FileField(upload_to="%Y/%m/%d", verbose_name="Image path"),
                ),
                ("img_order", models.PositiveSmallIntegerField(verbose_name="Order")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
                "db_table": "product_images",
                "unique_together": {("img_order", "product")},
            },
        ),
    ]
