# Generated by Django 4.2.3 on 2023-08-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_productcategoryoption_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="img_path",
            field=models.ImageField(upload_to="%Y/%m/%d", verbose_name="Image path"),
        ),
    ]
