# Generated by Django 4.2.4 on 2023-08-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_price_alter_product_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategoryoption",
            name="category",
        ),
        migrations.AddField(
            model_name="productcategory",
            name="options",
            field=models.ManyToManyField(
                blank=True,
                db_table="category_options_m2m",
                related_name="categories",
                to="product.productcategoryoption",
            ),
        ),
    ]
