# Generated by Django 4.2.4 on 2023-08-03 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_remove_productcategoryoption_category_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductCategoryOption",
            new_name="ProductOption",
        ),
        migrations.AlterModelOptions(
            name="productoption",
            options={
                "verbose_name": "Product option",
                "verbose_name_plural": "Product options",
            },
        ),
    ]
