# Generated by Django 4.2.4 on 2023-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_productoption_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmanufacturer",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
