# Generated by Django 4.2.4 on 2023-08-31 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_alter_profile_groups_alter_profile_user_permissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user_id",
            new_name="user",
        ),
    ]
