# Generated by Django 4.2.5 on 2023-09-04 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0004_rename_user_id_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=32, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=32, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("U", "U")],
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="profile",
            table="user_profiles",
        ),
    ]
