# Generated by Django 4.2.3 on 2023-08-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategoryoption",
            options={
                "verbose_name": "Product category option",
                "verbose_name_plural": "Product category options",
            },
        ),
        migrations.RemoveField(
            model_name="productcategoryoption",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="options",
            field=models.ManyToManyField(
                blank=True,
                db_table="product_options_m2m",
                related_name="product",
                to="product.productcategoryoption",
            ),
        ),
    ]
