# Generated by Django 4.2.4 on 2023-08-03 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_rename_productcategoryoption_productoption_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productoption",
            table="product_options",
        ),
    ]
