# Generated by Django 4.2.4 on 2023-08-15 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_productmanufacturer_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="options",
        ),
    ]
