# Generated by Django 4.2.4 on 2023-08-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_remove_productcategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_luxury",
            field=models.BooleanField(default=False, verbose_name="Luxury"),
        ),
    ]
