# Generated by Django 4.2.4 on 2023-08-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_product_is_luxury"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="img_order",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Order"),
        ),
    ]
