# Generated by Django 4.2.5 on 2023-09-08 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_alter_productimage_img_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["img_order"],
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
            },
        ),
    ]
