# Generated by Django 4.2.5 on 2023-09-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_alter_productimage_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="options",
            field=models.ManyToManyField(
                blank=True,
                db_table="category_options_m2m",
                related_name="categories",
                to="product.productoption",
            ),
        ),
    ]
