# Generated by Django 4.2.5 on 2023-10-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_productcategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="siblings",
            field=models.ManyToManyField(to="product.product"),
        ),
    ]
