# Generated by Django 4.2.5 on 2023-10-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_product_siblings"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="main_card",
            field=models.BooleanField(default=False, verbose_name="Main card"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="sibling_name",
            field=models.CharField(
                default="11", max_length=256, verbose_name="Sibling name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="siblings",
            field=models.ManyToManyField(related_name="sibling", to="product.product"),
        ),
    ]
