# Generated by Django 4.2.5 on 2023-10-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_product_main_card_product_sibling_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="siblings",
            field=models.ManyToManyField(
                null=True, related_name="sibling", to="product.product"
            ),
        ),
    ]
