# Generated by Django 4.2.7 on 2024-01-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0018_alter_product_siblings"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[
                    ("UAH", "Ukrainian Hryvnia"),
                    ("USD", "United States Dollar"),
                    ("EUR", "Euro"),
                ],
                default="UAH",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
    ]
