# Generated by Django 4.2.9 on 2024-02-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_currency_productcurrency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="abbreviation",
            field=models.CharField(
                max_length=3, unique=True, verbose_name="abbreviation"
            ),
        ),
    ]
