# Generated by Django 4.2.7 on 2024-02-05 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_remove_product_currency"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="price_is_positive",
        ),
    ]
