# Generated by Django 4.2.7 on 2024-02-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0022_currency_remove_product_price_productcurrency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="abbreviation",
            field=models.CharField(max_length=3, verbose_name="abbreviation"),
        ),
    ]
