PRODUCT_NAME_MIN_LENGTH = 2
PRODUCT_NAME_MAX_LENGTH = 256

PRODUCT_MANUFACTURER_NAME_MIN_LENGTH = 2
PRODUCT_MANUFACTURER_NAME_MAX_LENGTH = 256

PRODUCT_CATEGORY_NAME_MIN_LENGTH = 2
PRODUCT_CATEGORY_NAME_MAX_LENGTH = 256

PRODUCT_PRICE_MAX_DIGITS = 8  # 123456.78
