# Generated by Django 4.2.5 on 2024-01-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0003_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
