# Generated by Django 4.2.5 on 2024-01-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0005_alter_user_email_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
