# Generated by Django 4.2.5 on 2024-01-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0006_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Last name"),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("C", "Female"), ("U", "Undefined")],
                default="U",
                max_length=1,
                verbose_name="Sex",
            ),
        ),
    ]
