name: tests
run-name: ${{ github.actor }} tests check
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-django
      - name: Run ruff
        run: ruff check --format=github --select E,F,D --ignore D100,D104,D105,D106,D107,F821 src
      - name: pytest
        run: pytest
